feat: add 3D OSM building tiles
reearth/reearth pull request #340
Opened 2022-09-13 01:41 UTC by nina992

# Overview
 OSM Buildings is a 3D buildings layer covering the entire world. It's available as a 3D Tileset on Cesium.
we modified reearth back end in  way that allows the user to add OSM building 3d Tileset as a layer in his project by providing him with an interface to chose which tiles to show on the map.

## What I've done
- modify manifes.yml and add the new attributes related to 3D OSM building tiles.
- add the Japanese translation to manifest.ja.yml 

## What I haven't done

## How I tested

## Which point I want you to review particularly

## Memo

2022-09-13 04:29 UTC, rot1024 requested changes

2022-09-13 04:29 UTC, rot1024 commented on server/pkg/builtin/manifest_ja.yml
> +            description: A path to tileset.json in 3D tiles
Revert it to Japanese
This is a translation file

2022-09-13 04:29 UTC, rot1024 commented on server/pkg/builtin/manifest_ja.yml
> +            title: Source type
種類

2022-09-13 04:29 UTC, rot1024 commented on server/pkg/builtin/manifest_ja.yml
> +            description: choose the tiles source type between 3D tileset or OSM building.
3Dタイルの種類を選択します。

2022-09-13 04:29 UTC, rot1024 commented on server/pkg/builtin/manifest.yml
> +              availableIf:
Style should be usable for OSM also

2022-09-13 04:58 UTC, rot1024 requested changes

2022-09-13 04:58 UTC, rot1024 commented on server/pkg/builtin/manifest.yml
> +                - key: OSM
```suggestion
                - key: osm
```

2022-09-14 00:36 UTC, KaWaite commented on server/pkg/builtin/manifest.yml
> +              description: choose the tiles source type between 3D tileset or OSM building.
```suggestion
              description: Choose between an external 3D tileset or the OSM building 3d tileset.
```

2022-09-14 08:06 UTC, KaWaite approved these changes

2022-09-14 08:15 UTC, rot1024 approved these changes

2022-09-14 08:21 UTC, HideBa approved these changes

2022-09-14 08:23 UTC, merged