feat(server): support style and layer duplication
reearth/reearth pull request #911
Opened 2024-03-06 13:45 UTC by akiyatomohiro

# Overview

## What I've done

## What I haven't done

## How I tested

## Which point I want you to review particularly

## Memo

2024-03-11 20:24 UTC, pyshx requested changes
Neat, LGTM!
Please add small test for both of these operation in `server/e2e/gql_*_test.go` file 🙏🏼

2024-03-12 00:07 UTC, akiyatomohiro commented
> Neat, LGTM! Please add small test for both of these operation in `server/e2e/gql_*_test.go` file 🙏🏼

Thank you for your confirmation!
I understand.

2024-03-12 12:41 UTC, akiyatomohiro commented
@pyshx 
I fixed e2e test.
Please confirm.

2024-03-12 13:14 UTC, pyshx approved these changes

2024-03-12 13:18 UTC, merged